SET C51INC=D:\KEIL\C51\Inc;D:\KEIL\C51\Inc\STC
SET C51LIB=D:\KEIL\C51\Lib
SET CPU_TYPE=STC15F2K60S2 Series
SET CPU_VENDOR=STC
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x00A8C000
"D:\KEIL\C51\BIN\A51.EXE" @".\Objects\STARTUP._ia"
"D:\KEIL\C51\BIN\C51.EXE" @".\Objects\main.__i"
"D:\KEIL\C51\BIN\C51.EXE" @".\Objects\KEY.__i"
"D:\KEIL\C51\BIN\C51.EXE" @".\Objects\LED.__i"
"D:\KEIL\C51\BIN\C51.EXE" @".\Objects\AD.__i"
"D:\KEIL\C51\BIN\C51.EXE" @".\Objects\Nixie.__i"
"D:\KEIL\C51\BIN\C51.EXE" @".\Objects\Timer.__i"
"D:\KEIL\C51\BIN\C51.EXE" @".\Objects\RB.__i"
"D:\KEIL\C51\BIN\C51.EXE" @".\Objects\iic.__i"
"D:\KEIL\C51\BIN\C51.EXE" @".\Objects\Delay.__i"
"D:\KEIL\C51\BIN\BL51.EXE" @".\Objects\Project.lnp"
"D:\KEIL\C51\BIN\OH51.EXE" ".\Objects\Project" 
